Critical security fix plus setup rule

diff --git a/runcmd/exercise/Makefile b/runcmd/exercise/Makefile
--- a/runcmd/exercise/Makefile
+++ b/runcmd/exercise/Makefile
@@ -59,15 +59,14 @@ proj_src += $(foreach i, $(noinst_bin:%=%_obj), $($i:%.o=%.c))
 
 proj_dep = $(proj_src:%.c=%.d)  # For building
 
-
 ifneq (,$(strip $(proj_src)))   # For projects with no C sources
 proj_headers += $(filter %.h, $(shell $(CC) $(CPP_FLAGS) $(CPPFLAGS) -I. -MM -MG -MT "" $(proj_src)) )
 endif
-
 proj_headers += $(inst_headers) # For distribution
 
-EXTRA_DIST += Makefile config.mk local.mk test.mk README COPYING AUTHORS 
+RECOMMENDED = README COPYING AUTHORS INSTALL 
 
+EXTRA_DIST += Makefile config.mk local.mk test.mk $(foreach f, $(RECOMMENDED), $(wildcard $f))
 
 #
 # Rules
@@ -76,7 +75,23 @@ EXTRA_DIST += Makefile config.mk local.mk test.mk README COPYING AUTHORS
 # Build everything
 
 
-all static : $(gendist_files) $(lib_all) $(bin) $(noinst_bin) 
+all static : safety $(gendist_files) $(lib_all) $(bin) $(noinst_bin) 
+
+#
+# Safety
+#
+
+CRITICALNAMES = PROJECT bin noinst_bin lib
+
+safety: $(CRITICALNAMES:%=%_check)
+
+$(CRITICALNAMES:%=%_check) : %_check : 
+	@for i in $($*) ; do if test -z $${i##*/*} || test -z {i%%*/*} ; then echo "invalid config variable $*: $$i is not a valid name"; exit 1; fi; done
+	@for i in $($*) ; do if test -z $${i#.}    || test -z $${i#..} ; then echo "invalid config variable $*: $$i is not a valid name"; exit 1; fi; done	
+
+
+# Use GNU make secondary expansion
+
 
 .SECONDEXPANSION:
 
@@ -151,7 +166,7 @@ endif
 %-pic.d : %.c
 	$(CC) $(CPP_FLAGS) $(CPPFLAGS) -I. -MM -MG -MT '$(<:.c=-pic.o) $@' $< > $@
 
-ifeq (,$(filter clean uninstall, $(MAKECMDGOALS))) # Don't do it if not needed
+ifeq (,$(filter clean uninstall setup help, $(MAKECMDGOALS))) # Don't do it if not needed
 -include $(proj_dep)
 endif
 
@@ -220,3 +235,34 @@ test:	all tests_setup
 
 gendist.mk local.mk : 
 	touch $@
+
+help:
+	@echo "To be written"
+
+
+## Recommended stuff
+
+
+setup:
+	@n=0; for f in $(RECOMMENDED); do \
+            if test ! -f $$f; then n=1; $(MAKE) -s $$f.setup 2>/dev/null; fi;\
+        done; if test "$$n" != 0; then echo "Setup completed"; else echo "Everything already all set"; fi
+
+
+
+$(RECOMMENDED:%=%.setup):
+	@echo -n "Trying project rule for building $(@:%.setup=%)... "
+	@if ! $(MAKE)  -s $(@:%.setup=%) 2>/dev/null; then \
+	    echo -n "none found.\nTrying default rule for building $(@:%.setup=%)... ";\
+            if ! $(MAKE) -s $(@:%.setup=%.default) 2>/dev/null; then \
+               echo "none found.\nFailling back to last resort for $(@:%.setup=%)... created empty file"; \
+                    echo "$(PROJECT)" > $(@:%.setup=%); \
+	    else\
+              echo "default used.";\
+            fi;\
+        fi
+
+INSTALL.default : 
+	@echo "Default install rules" > $(@:%.default=%)
+
+
